server:
  port: 8040
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    prefer-ip-address: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
                            
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
